DO BEGIN
    DECLARE table_exists INT;

    SELECT COUNT(*) INTO table_exists
    FROM TABLES WHERE TABLE_NAME = 'SAP_SYSTEM_LOGS';
    IF :table_exists = 0 THEN
        EXEC 'CREATE TABLE SAP_SYSTEM_LOGS (
            ID                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            TIMESTAMP         TIMESTAMP NOT NULL,
            LOG_TYPE          NVARCHAR(20) NOT NULL,
            HTTP_STATUS_CODE  INTEGER,
            CLIENT_IP         NVARCHAR(50),
            SERVICE_ID        NVARCHAR(100),
            WINDOW_START      TIMESTAMP,
            INGESTED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )';
        EXEC 'CREATE INDEX IDX_SYSLOG_TIMESTAMP ON SAP_SYSTEM_LOGS (TIMESTAMP DESC)';
        EXEC 'CREATE INDEX IDX_SYSLOG_LOGTYPE   ON SAP_SYSTEM_LOGS (LOG_TYPE)';
        EXEC 'CREATE INDEX IDX_SYSLOG_CLIENT_IP ON SAP_SYSTEM_LOGS (CLIENT_IP)';
    END IF;

    SELECT COUNT(*) INTO table_exists
    FROM TABLES WHERE TABLE_NAME = 'SAP_LLM_LOGS';
    IF :table_exists = 0 THEN
        EXEC 'CREATE TABLE SAP_LLM_LOGS (
            ID                    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            TIMESTAMP             TIMESTAMP NOT NULL,
            LOG_TYPE              NVARCHAR(20) NOT NULL,
            LLM_MODEL_ID          NVARCHAR(100),
            LLM_STATUS            NVARCHAR(50),
            LLM_COST_USD          DOUBLE,
            LLM_RESPONSE_TIME_MS  INTEGER,
            WINDOW_START          TIMESTAMP,
            INGESTED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )';
        EXEC 'CREATE INDEX IDX_LLMLOG_TIMESTAMP ON SAP_LLM_LOGS (TIMESTAMP DESC)';
        EXEC 'CREATE INDEX IDX_LLMLOG_STATUS    ON SAP_LLM_LOGS (LLM_STATUS)';
        EXEC 'CREATE INDEX IDX_LLMLOG_MODEL     ON SAP_LLM_LOGS (LLM_MODEL_ID)';
    END IF;

    SELECT COUNT(*) INTO table_exists
    FROM TABLES WHERE TABLE_NAME = 'ANOMALY_RESULTS';
    IF :table_exists = 0 THEN
        EXEC 'CREATE TABLE ANOMALY_RESULTS (
            ID             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            SOURCE_TABLE   NVARCHAR(20) NOT NULL,
            SOURCE_ID      BIGINT NOT NULL,
            IS_ANOMALY     BOOLEAN NOT NULL DEFAULT FALSE,
            ANOMALY_SCORE  DOUBLE,
            ANOMALY_TYPE   NVARCHAR(50),
            CLUSTER_ID     INTEGER,
            ML_MODEL_VER   NVARCHAR(20) DEFAULT ''v1'',
            DETECTED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )';
        EXEC 'CREATE INDEX IDX_ANOMALY_IS_ANOMALY  ON ANOMALY_RESULTS (IS_ANOMALY)';
        EXEC 'CREATE INDEX IDX_ANOMALY_DETECTED_AT ON ANOMALY_RESULTS (DETECTED_AT DESC)';
        EXEC 'CREATE INDEX IDX_ANOMALY_SOURCE      ON ANOMALY_RESULTS (SOURCE_TABLE, SOURCE_ID)';
    END IF;

    SELECT COUNT(*) INTO table_exists
    FROM TABLES WHERE TABLE_NAME = 'INCIDENTS';
    IF :table_exists = 0 THEN
        EXEC 'CREATE TABLE INCIDENTS (
            ID              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            ANOMALY_ID      BIGINT NOT NULL,
            SEVERITY        NVARCHAR(20),
            ATTACK_TYPE     NVARCHAR(100),
            ALERT_SENT      BOOLEAN DEFAULT FALSE,
            WEBHOOK_STATUS  NVARCHAR(50) DEFAULT ''PENDING'',
            RESOLVED        BOOLEAN DEFAULT FALSE,
            CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )';
        EXEC 'CREATE INDEX IDX_INCIDENT_SEVERITY   ON INCIDENTS (SEVERITY)';
        EXEC 'CREATE INDEX IDX_INCIDENT_RESOLVED   ON INCIDENTS (RESOLVED)';
        EXEC 'CREATE INDEX IDX_INCIDENT_CREATED_AT ON INCIDENTS (CREATED_AT DESC)';
    END IF;
END;
