-- Q1: Latest 50 system logs
SELECT * FROM SAP_SYSTEM_LOGS
ORDER BY TIMESTAMP DESC
LIMIT 50;

-- Q2: All confirmed anomalies not yet in INCIDENTS
SELECT A.*
FROM ANOMALY_RESULTS A
LEFT JOIN INCIDENTS I ON A.ID = I.ANOMALY_ID
WHERE A.IS_ANOMALY = TRUE
AND I.ID IS NULL;

-- Q3: Open incidents with full log detail
SELECT
    I.ID, I.SEVERITY, I.ATTACK_TYPE,
    I.ALERT_SENT, I.WEBHOOK_STATUS,
    I.CREATED_AT,
    L.CLIENT_IP, L.SERVICE_ID,
    L.HTTP_STATUS_CODE, L.LOG_TYPE
FROM INCIDENTS I
JOIN ANOMALY_RESULTS A ON I.ANOMALY_ID = A.ID
JOIN SAP_SYSTEM_LOGS L ON A.SOURCE_ID = L.ID
WHERE I.RESOLVED = FALSE
ORDER BY I.CREATED_AT DESC;

-- Q4: Top 10 attacking IPs
SELECT CLIENT_IP, COUNT(*) AS ATTEMPTS,
       MAX(TIMESTAMP) AS LAST_SEEN
FROM SAP_SYSTEM_LOGS
WHERE LOG_TYPE = 'SECURITY'
AND CLIENT_IP IS NOT NULL
GROUP BY CLIENT_IP
ORDER BY ATTEMPTS DESC
LIMIT 10;

-- Q5: LLM cost and performance summary
SELECT
    LLM_MODEL_ID,
    LLM_STATUS,
    COUNT(*) AS TOTAL_CALLS,
    ROUND(SUM(LLM_COST_USD), 4) AS TOTAL_COST_USD,
    ROUND(AVG(LLM_RESPONSE_TIME_MS), 0) AS AVG_RESPONSE_MS
FROM SAP_LLM_LOGS
GROUP BY LLM_MODEL_ID, LLM_STATUS
ORDER BY TOTAL_COST_USD DESC;

-- Q6: KPI summary for dashboard
SELECT
    (SELECT COUNT(*) FROM SAP_SYSTEM_LOGS) AS TOTAL_SYSTEM_LOGS,
    (SELECT COUNT(*) FROM SAP_LLM_LOGS) AS TOTAL_LLM_LOGS,
    (SELECT COUNT(*) FROM ANOMALY_RESULTS
     WHERE IS_ANOMALY = TRUE) AS TOTAL_ANOMALIES,
    (SELECT COUNT(*) FROM INCIDENTS
     WHERE RESOLVED = FALSE) AS OPEN_INCIDENTS,
    (SELECT COUNT(*) FROM INCIDENTS
     WHERE ALERT_SENT = TRUE) AS ALERTS_SENT
FROM DUMMY;
