CREATE TABLE INCIDENTS (
    ID              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ANOMALY_ID      BIGINT NOT NULL,
    SEVERITY        NVARCHAR(20),
    ATTACK_TYPE     NVARCHAR(100),
    ALERT_SENT      BOOLEAN DEFAULT FALSE,
    WEBHOOK_STATUS  NVARCHAR(50) DEFAULT 'PENDING',
    RESOLVED        BOOLEAN DEFAULT FALSE,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_INCIDENT_SEVERITY   ON INCIDENTS (SEVERITY);
CREATE INDEX IDX_INCIDENT_RESOLVED   ON INCIDENTS (RESOLVED);
CREATE INDEX IDX_INCIDENT_CREATED_AT ON INCIDENTS (CREATED_AT DESC);
