CREATE TABLE PIPELINE_HEALTH (
    ID                    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CYCLE_START           TIMESTAMP NOT NULL,
    CYCLE_END             TIMESTAMP NOT NULL,
    RECORDS_PROCESSED     INTEGER DEFAULT 0,
    ANOMALIES_DETECTED    INTEGER DEFAULT 0,
    STATUS                NVARCHAR(20) DEFAULT 'SUCCESS',
    ERROR_MESSAGE         NVARCHAR(500),
    POLL_INTERVAL_SECONDS INTEGER
);

CREATE INDEX IDX_PIPELINE_CYCLE_START ON PIPELINE_HEALTH (CYCLE_START DESC);
CREATE INDEX IDX_PIPELINE_STATUS      ON PIPELINE_HEALTH (STATUS);
