CREATE TABLE SAP_SYSTEM_LOGS (
    ID                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIMESTAMP         TIMESTAMP NOT NULL,
    LOG_TYPE          NVARCHAR(20) NOT NULL,
    HTTP_STATUS_CODE  INTEGER,
    CLIENT_IP         NVARCHAR(50),
    SERVICE_ID        NVARCHAR(100),
    WINDOW_START      TIMESTAMP,
    INGESTED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_SYSLOG_TIMESTAMP ON SAP_SYSTEM_LOGS (TIMESTAMP DESC);
CREATE INDEX IDX_SYSLOG_LOGTYPE   ON SAP_SYSTEM_LOGS (LOG_TYPE);
CREATE INDEX IDX_SYSLOG_CLIENT_IP ON SAP_SYSTEM_LOGS (CLIENT_IP);
