CREATE TABLE SAP_LLM_LOGS (
    ID                    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIMESTAMP             TIMESTAMP NOT NULL,
    LOG_TYPE              NVARCHAR(20) NOT NULL,
    LLM_MODEL_ID          NVARCHAR(100),
    LLM_STATUS            NVARCHAR(50),
    LLM_COST_USD          DOUBLE,
    LLM_RESPONSE_TIME_MS  INTEGER,
    WINDOW_START          TIMESTAMP,
    INGESTED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_LLMLOG_TIMESTAMP ON SAP_LLM_LOGS (TIMESTAMP DESC);
CREATE INDEX IDX_LLMLOG_STATUS    ON SAP_LLM_LOGS (LLM_STATUS);
CREATE INDEX IDX_LLMLOG_MODEL     ON SAP_LLM_LOGS (LLM_MODEL_ID);
